### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by nikvs216** [zackmawaldi/YouTube-shorts-generator#10]
Traceback (most recent call last):
  File "C:\YouTube-shorts-generator-main\main.py", line 17, in <module>
    os.remove(directory + file)
PermissionError: [WinError 5] Permissions denied 
Runned with CMD as a Admin.
Anyone ideas?

**Comment by zackmawaldi** [comment]
Hi, same error is mentioned before. Check out: https://github.com/zackmawaldi/YouTube-shorts-generator/issues/6
It seems to be a common theme with windows and python editing stuff. If you do enough googling, I think you'll find a solution. I worked on this in Linux and Mac. Hope this helps!

**Comment by nikvs216** [comment]
On which version of Python did you worked on?

**Comment by zackmawaldi** [comment]
Python 3.8 if I recall correctly. 3+ for sure

**Comment by jxck13** [comment]
Hi @zackmawaldi. I ran into this same problem on Windows 11, and I have tried literally every solution to fix it, but it just doesn't work :( It would be really helpful if you could take a better look at this. Thank you.

Traceback (most recent call last):
  File "C:\Users\me\PycharmProjects\YouTube-shorts-generator\main.py", line 17, in <module>
    os.remove(directory + file)
PermissionError: [WinError 5] Access is denied: 'temp_clips/redvid_temp'

Process finished with exit code 1

**Comment by zackmawaldi** [comment]
@jxck13 Hmm... I updated the code recently, can you retry it with the new code? (and also sorry for late reply, life got super busy!)

**Comment by BuddyNotFound** [comment]
> @jxck13 Hmm... I updated the code recently, can you retry it with the new code? (and also sorry for late reply, life got super busy!)

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'videos2\\main_clip.mp4'

error is still here (windows 11,  3.11.4)

**Comment by xdrushxd** [comment]
Got the same error, the video gets downloaded and the program did work once.

PermissionError: [WinError 32] Het proces heeft geen toegang tot het bestand omdat het door een ander
proces wordt gebruikt: 'temp_clips\\main_clip.mp4'

Retrying...
